/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BookStoreManagement;

import java.sql.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.sql.*;
import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import static java.nio.file.Files.size;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author user
 */
public class Dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegisterBook
     */
    public Dashboard() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI b = (BasicInternalFrameUI) this.getUI();
        b.setNorthPane(null);
        aBooks();
        mBooks();
    }
    Statement st;
    ResultSet rs;
    Connection con;
    PreparedStatement pst;
    String filepath;

    private void aBooks() {
        try {
            con = database.connectDB();
            st = con.createStatement();
            rs = st.executeQuery("select count(*) from abooks");
            if (rs.next()) {
                jLabel1.setText(String.valueOf(rs.getString(1)));
            } else {
                jLabel1.setText("0");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                st.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    private void mBooks() {
        try {
            con = database.connectDB();
            st = con.createStatement();
            rs = st.executeQuery("select count(*) from mbooks");
            if (rs.next()) {
                jLabel2.setText(String.valueOf(rs.getString(1)));
            } else {
                jLabel2.setText("0");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                st.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookStoreManagement/giphy (2).gif"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 17, 531, 92));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookStoreManagement/Boy-Reading-in-Library_1080x600.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 1080, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        try {
            DateTimeFormatter dt = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            LocalDateTime now = LocalDateTime.now();
            String date = dt.format(now);
            con = database.connectDB();
            String query7 = "select * from abooks";
            pst = con.prepareStatement(query7);
            rs = pst.executeQuery();

            JFileChooser chooser = new JFileChooser();
            chooser.setSelectedFile(new File("Available Books" + "" + ".pdf"));
            int chooseDialog = chooser.showSaveDialog(null);
            if (chooseDialog == JFileChooser.APPROVE_OPTION) {
                filepath = chooser.getSelectedFile().getPath();
            }
            Document mydocument = new Document();
            PdfWriter.getInstance(mydocument, new FileOutputStream(filepath));
            PdfPTable table = new PdfPTable(3);
            mydocument.open();
            float[] columnWidth = new float[]{18, 15, 7};
            table.setWidths(columnWidth);
            table.setWidthPercentage(100);
            table.setWidthPercentage(100);
            mydocument.add(new Paragraph("                   BOOK STORE MANAGEMENT ", FontFactory.getFont(FontFactory.TIMES_BOLDITALIC, 20, Font.ITALIC)));
            mydocument.add(new Paragraph(" "));
            mydocument.add(new Paragraph("                                         AVAILABLE BOOKS", FontFactory.getFont(FontFactory.TIMES_BOLD, 17, Font.PLAIN)));
            mydocument.add(new Paragraph(" "));
            table.addCell(new PdfPCell(new Paragraph("Book Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph("Author Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph("Price", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLD))));

            while (rs.next()) {
                table.addCell(new PdfPCell(new Paragraph(rs.getString("bname"), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.PLAIN))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString("aname"), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.PLAIN))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString("price"), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.PLAIN))));
            }
            mydocument.add(table);
            mydocument.add(new Paragraph(" "));
            mydocument.add(new Paragraph(date, FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.PLAIN)));
            mydocument.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        try {
            DateTimeFormatter dt = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            LocalDateTime now = LocalDateTime.now();
            String date = dt.format(now);
            con = database.connectDB();
            String query7 = "select * from mbooks";
            pst = con.prepareStatement(query7);
            rs = pst.executeQuery();

            JFileChooser chooser = new JFileChooser();
            chooser.setSelectedFile(new File("My Books" + "" + ".pdf"));
            int chooseDialog = chooser.showSaveDialog(null);
            if (chooseDialog == JFileChooser.APPROVE_OPTION) {
                filepath = chooser.getSelectedFile().getPath();
            }
            Document mydocument = new Document();
            PdfWriter.getInstance(mydocument, new FileOutputStream(filepath));
            PdfPTable table = new PdfPTable(3);
            mydocument.open();
            float[] columnWidth = new float[]{18, 15, 7};
            table.setWidths(columnWidth);
            table.setWidthPercentage(100);
            table.setWidthPercentage(100);
            mydocument.add(new Paragraph("                   BOOK STORE MANAGEMENT ", FontFactory.getFont(FontFactory.TIMES_BOLDITALIC, 20, Font.ITALIC)));
            mydocument.add(new Paragraph(" "));
            mydocument.add(new Paragraph("                                         MY BOOKS", FontFactory.getFont(FontFactory.TIMES_BOLD, 17, Font.PLAIN)));
            mydocument.add(new Paragraph(" "));
            table.addCell(new PdfPCell(new Paragraph("Book Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph("Author Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph("Price", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLD))));

            while (rs.next()) {
                table.addCell(new PdfPCell(new Paragraph(rs.getString("bname"), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.PLAIN))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString("aname"), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.PLAIN))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString("price"), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.PLAIN))));
            }
            mydocument.add(table);
            mydocument.add(new Paragraph(" "));
            mydocument.add(new Paragraph(date, FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.PLAIN)));
            mydocument.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jPanel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
